/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Text Input Service
 #	author : miyako
 #	2015/04/22
 #
 # --------------------------------------------------------------------------------*/



// --- Input Source
void INPUT_SOURCE_Get_for_language(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_SET(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_Get(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_Get_category(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_Get_ASCII(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_Get_icon(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_Get_name(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_Get_type(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_DISABLE(sLONG_PTR *pResult, PackagePtr pParams);
void INPUT_SOURCE_ENABLE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Keyboard Layout
void KEYBOARD_LAYOUT_Get_ASCII(sLONG_PTR *pResult, PackagePtr pParams);
void KEYBOARD_LAYOUT_SET_OVERRIDE(sLONG_PTR *pResult, PackagePtr pParams);
void KEYBOARD_LAYOUT_Get(sLONG_PTR *pResult, PackagePtr pParams);
void KEYBOARD_LAYOUT_Get_override(sLONG_PTR *pResult, PackagePtr pParams);
